# Data sources

Our primary data source is IMDb (Internet Movie Database, https://datasets.imdbws.com) which is owned and operated by IMDb.com, Inc., a subsidiary of Amazon. Sources for the IMDb data include on-screen credits, press kits, official bios, autobiographies, and interviews. While data from this site is collected and verified by IMDb with studios and filmmakers, the bulk of the information is submitted by people in the industry and website visitors.  

The IMDb datasets we used for this project have a consistent data format which utilizes an alphanumeric unique identifier for the title of each film and an alphanumeric unique identifier for each name/person (director, actor etc.). Types of variables in the dataset include strings, arrays of strings, integers and booleans. The only issue we came across when using this dataset was the way missing values and unknown data were handled which we will further discuss in the missing values chapter. 

Since IMDb does not contain salary data and one the topics we were interested in exploring was the gender pay gap in the film industry, we incorporated salary data from Forbes (https://www.forbes.com/sites/natalierobehmed/2017/08/22/full-list-the-worlds-highest-paid-actors-and-actresses-2017/?sh=5b3efcbb3751). Unfortunately, we could not find a full dataset of actor/actress salary information without a paid subscription. Although this type of data gathering is not ideal, we decided to pivot around the restricted access to the film industry’s salary data and copied the data from Forbes into a csv. Since this data was manually inputted, we assured it was in a format consistent to the IMDb data and all unique identifiers matched.
