# Data transformation

Most of our data transformation involved merging and filtering different IMDb datasets. For instance, to prepare our data for a Cleveland dot plot of top ranked actors/actresses and their respective salaries we first merged a dataset that consisted of actor/actress information with a dataset that contained title and rating data for each film. After this initial merge we were able to calculate an average rating for each actor/actress. We then created a new column that assigned each actor/actress a rank and grouped the top actor with the top actress in the Cleveland dot plot to visualize salary difference. 

Another interesting data transformation was done to create a graph of median age of lead actors/ actresses from 1920 to 2020. To get the data in the appropriate format we first needed to calculate the age of lead actors and actresses for all movies. We did this by merging a movie dataset with an actor/actress general information dataset to get the start year of each film and the birth year of each actor/actress. Once we had this information were able to graph the median age of actors and actresses over time to visualize any age bias between genders.
